version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"  # Expose the web app port
    depends_on:
      - db
  db:
    image: postgres:13  # Use the official PostgreSQL image
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: myapp  # Replace with your app's DB name
volumes:
  db_data:
